site_name: Documentación Experthub API
site_description: Documentación del API de Experthub.

docs_dir: '../../docs/es'
site_dir: '../../site/es'

theme:
    custom_dir: ../../overrides/
    logo: assets/Logo.svg
    favicon: assets/imagotipo.svg
    name: material
    language: es
    palette:
        - scheme: experticket
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: blue grey
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.instant #cargar las páginas como vistas parciales
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top #botón de volver arriba
        #- navigation.indexes #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration 
        #- toc.integrate #tabla de contenido integrada con barra de navegación
        #- content.tabs.link
extra_css:
    - stylesheets/extra.css
extra:
    alternate:
        - name: English
          link: /experthubApiDocs/en/
          lang: en
        - name: Español
          link: /experthubApiDocs/es/
          lang: es
    social:
      - link: mailto:integrations@experticket.com
        icon: fontawesome/solid/envelope
        name: Email de contacto
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  #- meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search:
      lang: 
        - es
#copyright: Copyright &copy; Experticket

nav:
    - Inicio: index.md
    - Documentación:
      - Introducción: docs/intro.md 
      - Interfaz de comunicación: docs/connection.md
      - Especificación de datos: docs/struct.md
      - Actividades:
        - Catálogo: docs/activity/catalog.md
        - Última fecha de actualización del catálogo: docs/activity/lastCatalogUpdatedDate.md
        - Precios en tiempo real: docs/activity/realTimePrices.md
        - Sesiones: docs/activity/sessions.md
        - Comprobar sesiones auto asignadas: docs/activity/autoAssignSession.md
        - Aforo disponible: docs/activity/availability.md
        - Reglas de flujo de venta: 
          - Obtener reglas: docs/activity/saleFlowRules.md
          - Comprobar reglas aplicadas: docs/activity/checkSaleFlowRules.md
        - Métodos de pago: docs/activity/paymentMethods.md
        - Métodos de entrega:
          - Obtener métodos de entrega: docs/activity/deliveryMethods.md
          - Comprobar método de entrega: docs/activity/checkDeliveryMethods.md
          - Canje de tickets: docs/activity/ticketExchange.md
        - Comprobar cupones descuento: docs/activity/checkDiscountCoupons.md
        - Etiquetas: docs/activity/tags.md
      - Alojamiento:
        - Catálogo básico: docs/accommodation/basicCatalog.md
        - Catálogo completo: docs/accommodation/fullCatalog.md
      - Paquetes:
        - Prepaquetes: docs/package/prePackage.md
        - Catalogo básico: docs/package/basicCatalog.md
        - Catálogo extendido: docs/package/extendedCatalog.md
        - Disponibilidad de fechas: docs/package/availableDates.md
        - Precios: docs/package/pricesAndCancellationsConditions.md
      - Proceso de compra:
        - Introducción: docs/shoppingCart/introduction.md
        - Creación: docs/shoppingCart/create.md
        - Añadir al carrito: docs/shoppingCart/add.md
        - Eliminar elemento del carrito: docs/shoppingCart/remove.md
        - Reserva de precios: docs/shoppingCart/confirm.md
        - Cancelación de la reserva: docs/shoppingCart/cancelConfirm.md
        - Confirmación de la reseva: docs/shoppingCart/sale.md
        - Documentación: docs/shoppingCart/documentation.md
      - Anexos:
        - Códigos de error: docs/annex/errorCodes.md
    - FAQ: faq.md
    - Acerca de: about.md
