site_name: Documentación Experthub API
site_description: Documentación del API de Experthub.

docs_dir: '../../docs/es'
site_dir: '../../site/es'

theme:
    custom_dir: ../../overrides/
    logo: assets/Logo.png
    favicon: assets/imagotipo.svg
    name: material
    language: es
    palette:
        - scheme: experticket
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: blue grey
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
extra_css:
    - stylesheets/extra.css
extra:
    alternate:
        - name: English
          link: /en/
          lang: en
        - name: Español
          link: /es/
          lang: es
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: 
        - es

nav:
    - Principal: index.md
    - Acerca de: about.md
