site_name: Experthub API Documentation
site_description: API documentation for Experthub.

docs_dir: '../../docs/en'
site_dir: '../../site/en'

theme:
    custom_dir: ../../overrides/
    logo: assets/Logo.svg
    favicon: assets/imagotipo.svg
    name: material
    language: en
    palette:
        - scheme: experticket
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: blue grey
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.instant #cargar las páginas como vistas parciales
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top #botón de volver arriba
        #- navigation.indexes #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration 
        #- toc.integrate #tabla de contenido integrada con barra de navegación
        #- content.tabs.link
extra_css:
    - stylesheets/extra.css
extra:
    alternate:
        - name: English
          link: /en/
          lang: en
        - name: Español
          link: /es/
          lang: es
    social:
      - link: mailto:integrations@experticket.com
        icon: fontawesome/solid/envelope
        name: Contact email
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  #- meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search:
      lang: 
        - en
#copyright: Copyright &copy; Experticket

nav:
    - Home: index.md
    - Documentation:
      - Connection: docs/connection.md
      - Data specification: docs/struct.md
      - Activity:
        - Catalog: docs/activity/catalog.md
        - Last catalog update date: docs/activity/lastCatalogUpdatedDate.md
        - Available languages: docs/activity/availableLanguages.md
        - Real time prices: docs/activity/realTimePrices.md
        - Sessions: docs/activity/sessions.md
        - Check auto assigned sessions: docs/activity/autoAssignSession.md
        - Available capacity: docs/activity/availability.md
        - Ticket questions: docs/activity/CheckTicketsQuestions.md
        - Sale flow rules: docs/activity/checkSaleFlowRules.md
        - Gift cards: docs/activity/giftCards.md
        #- Payment methods: docs/activity/paymentMethods.md -> payment method information is returned in the reservation response.
        - Delivery methods:
          - Get delivery methods: docs/activity/deliveryMethods.md
          - Check delivery method: docs/activity/checkDeliveryMethods.md
          - Ticket exchange: docs/activity/ticketExchange.md
        - Check discount coupons: docs/activity/checkDiscountCoupons.md
        - Quote insurance policies: docs/activity/checkInsurancePolicies.md
        - Tags: docs/activity/tags.md
      - Accommodation:
        - Basic catalog: docs/accommodation/basicCatalog.md
        - Full catalog: docs/accommodation/fullCatalog.md
      - Packages:
        - Prepackages: docs/package/prePackage.md
        - Basic catalog: docs/package/basicCatalog.md
        - Full catalog: docs/package/fullCatalog.md
        - Available dates: docs/package/availableDates.md
        - Prices: docs/package/pricesAndCancellationsConditions.md
      - Purchase process:
        - Introduction: docs/shoppingCart/introduction.md
        - Create: docs/shoppingCart/create.md
        - Add to cart: docs/shoppingCart/add.md
        - Remove cart item: docs/shoppingCart/remove.md
        - Reserve products: docs/shoppingCart/confirm.md
        - Cancel reservation: docs/shoppingCart/cancelConfirm.md
        - Confirm reservation: docs/shoppingCart/sale.md
        - Sale documentation: docs/shoppingCart/documentation.md
        - Attach documents to a sale: docs/sale/saleAttachments.md
        - List of sales: docs/shoppingCart/listOfSales.md
      - Sale options:
        - Introduction: docs/sale/introduction.md
        - List of sales: docs/shoppingCart/listOfSales.md
        - Create cancellation request: docs/sale/saleCancellationRequest.md
        - List of cancellation requests: docs/sale/listOfSaleCancellationRequest.md
        - Sale documentation: docs/shoppingCart/documentation.md
        - Attach documents to a sale: docs/sale/saleAttachments.md
      - Annexes:
        - Activity: docs/annex/activity.en.md
        - Accommodation: docs/annex/accommodation.en.md
        - Combined product: docs/annex/combinedProduct.en.md
        - Client: docs/annex/client.en.md
        - Error codes: docs/annex/errorCodes.md
    #- FAQ: faq.md
    #- About: about.md
