name: Deploy GitHub Pages
on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install mkdocs-material" #instalar aquí todos los plugin o ejecutables necesarios
        run: pip install mkdocs-material 
      - name: "Build English Docs"
        run: mkdir -p site/en | mkdocs build -f config/en/mkdocs.yml
      - name: "Build Spanish Docs"
        run: mkdir site/es | mkdocs build -f config/es/mkdocs.yml
      - name: "Make Spanish Default"
        run: cp -r site/es/* site
      - name: "Deploy to Github Pages" #deploy las web creada a la rama gh-pages para que se muestren en la web
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}