name: ci 
on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: cd config/es
      - run: mkdocs gh-deploy --force
      - run: cd config/en
      - run: mkdocs gh-deploy --force